### ISSUE TITLE
Thread managed pool needed - getting file system gc error running osx native - not in docker/linux

### ISSUE THREAD

**Issue by obriensystems** [obrienlabs/magellan#11]
Request: http://192.168.100.145:8080/nbi/forward/packet?dnsFrom=192.168.100.145&dnsTo=192.168.100.156&from=8080&to=8080&delay=20
[2m2021-09-26 10:14:28.067[0;39m [32mDEBUG[0;39m [35m19555[0;39m [2m---[0;39m [2m[nio-8080-exec-5][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m Completed 200 OK
Response: 8098
[2m2021-09-26 10:14:28.130[0;39m [31mERROR[0;39m [35m19555[0;39m [2m---[0;39m [2m[o-8080-Acceptor][0;39m [36morg.apache.tomcat.util.net.Acceptor     [0;39m [2m:[0;39m Socket accept failed

java.io.IOException: Too many open files
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:466) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:72) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:95) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

[2m2021-09-26 10:14:28.191[0;39m [31mERROR[0;39m [35m19555[0;39m [2m---[0;39m [2m[o-8080-Acceptor][0;39m [36morg.apache.tomcat.util.net.Acceptor     [0;39m [2m:[0;39m Socket accept failed

**Comment by obriensystems** [comment]
moved the httpclient builder out of the method - what was wrong with me
7000 threads down to 60

**Comment by obriensystems** [comment]
<img width="742" alt="Screen Shot 2021-09-26 at 10 48 06" src="https://user-images.githubusercontent.com/24765473/134813068-3cc58eb0-7879-4e33-b9a7-cf68a59f3241.png">
